version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: org.pitest:pitest-maven
    versions:
    - 1.6.2
    - 1.6.3
    - 1.6.4
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.1
  - dependency-name: org.pitest:pitest-junit5-plugin
    versions:
    - "0.12"
